Error handling module complete and building

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,8 +5,9 @@ echo
 echo Compiling modules...
 echo
 
-fbc -mt -c "./src/fb/meld/lib/fault/fault.bas" || { echo; echo Failed to compile fault, build terminated; exit 1; }
 fbc -mt -c "./src/fb/meld/lib/core/core.bas" || { echo; echo Failed to compile core, build terminated; exit 1; }
+fbc -mt -c "./src/fb/meld/lib/fault/fault.bas" || { echo; echo Failed to compile fault, build terminated; exit 1; }
+fbc -mt -c "./src/fb/meld/lib/error-handling/error-handling.bas" || { echo; echo Failed to compile error-handling, build terminated; exit 1; }
 
 fbc -mt -c "./src/fb/shared/lib/bst/bst.bas" || { echo; echo Failed to compile bst, build terminated; exit 1; }
 fbc -mt -c "./src/fb/shared/lib/console/console.bas" || { echo; echo Failed to compile console, build terminated; exit 1; }
@@ -19,6 +20,7 @@ fbc -mt -c "./src/fb/shared/lib/resource-container/resource-container.bas" || { 
 fbc -mt -C "./src/fb/tester/tester.bas" -x "./tester" \
 	"./src/fb/meld/lib/core/core.o" \
 	"./src/fb/meld/lib/fault/fault.o" \
+	"./src/fb/meld/lib/error-handling/error-handling.o" \
 	"./src/fb/shared/lib/bst/bst.o" \
 	"./src/fb/shared/lib/console/console.o" \
 	"./src/fb/shared/lib/identity/identity.o" \
@@ -38,6 +40,7 @@ echo Building Meld Core...;
 fbc -mt -C "./src/fb/meld/meld.bas" -x "./meld" \
 	"./src/fb/meld/lib/core/core.o" \
 	"./src/fb/meld/lib/fault/fault.o" \
+	"./src/fb/meld/lib/error-handling/error-handling.o" \
 	"./src/fb/shared/lib/bst/bst.o" \
 	"./src/fb/shared/lib/console/console.o" \
 	"./src/fb/shared/lib/identity/identity.o" \
