First full unit test completed on list; testing started for error; some cleanup

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,11 +3,11 @@
 echo 'Starting Meld Core build';
 echo '';
 
-fbc -mt -C './src/fb/tester/tester.bas' -x './tester' || { echo ''; echo 'Test compilation failed, build terminating'; exit 1; }
+fbc -mt -C './src/fb/tester/tester.bas' -x './tester' || { echo ''; echo 'Test compilation failed, build terminated'; exit 1; }
 
 echo '';
 
-./tester || { echo ''; echo 'Test failed, build terminating'; exit 1; }
+./tester || { echo ''; echo 'Test failed, build terminated'; exit 1; }
 
 echo '';
 
