MR-7 - Meld main module rewrite and build

diff --git a/build/all b/build/all
--- a/build/all
+++ b/build/all
@@ -13,15 +13,15 @@ compileExternal () {
 
 echo Starting Meld Core build...
 echo
-echo Compiling modules...
-echo
+#echo Compiling modules...
+#echo
 
-compileExternal meld core
-compileExternal shared bst
-compileExternal shared iterator
-compileExternal shared list
-compileExternal shared paged-array
-compileExternal shared resource-container
+#compileExternal meld core
+#compileExternal shared bst
+#compileExternal shared iterator
+#compileExternal shared list
+#compileExternal shared paged-array
+#compileExternal shared resource-container
 
 #compile meld core
 #compile meld fault
@@ -36,12 +36,12 @@ compileExternal shared resource-container
 #compile shared paged-array
 #compile shared resource-container
 
-fbc -mt -C "./src/fb/tester/tester.bas" -x "./tester" \
-	|| { echo; echo Test compilation failed, build terminated; exit 1; }
+#fbc -mt -C "./src/fb/tester/tester.bas" -x "./tester" \
+#	|| { echo; echo Test compilation failed, build terminated; exit 1; }
 
-echo "";
+#echo "";
 
-./tester || { echo; echo Test failed, build terminated; exit 1; }
+#./tester || { echo; echo Test failed, build terminated; exit 1; }
 
 echo;
 echo Building Meld Core...;
